# Use root/example as user/password credentials
version: '3.1'
services:
  db:
    container_name: db
    image: mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password 
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    ports:
      - 8790:3306
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
